apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: "{{ .Values.backend.env.DB_HOST }}"
            - name: DB_PORT
              value: "{{ .Values.backend.env.DB_PORT }}"
            - name: DB_NAME
              value: "{{ .Values.backend.env.DB_NAME }}"
            - name: DB_USER
              value: "{{ .Values.backend.env.DB_USER }}"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD