apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  POSTGRES_DB: {{ .Values.postgres.db.name | b64enc }}
  POSTGRES_USER: {{ .Values.postgres.db.user | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgres.db.password | b64enc }}