apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: three-tier-project
  namespace: argocd
spec:
  description: Three tier with observability and monitoring
  sourceRepos:
    - 'https://github.com/tiwarishivam18/three-tier.git'
  destinations:
    - namespace: dev
      server: https://kubernetes.default.svc
    - namespace: prod
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'